### ISSUE TITLE
general TODO

### ISSUE THREAD

**Issue by catdad** [catdad-experiments/share-edit#25]
- [x] Share button should toast hint
- [x] Draw
- [x] Control draw brush size
- [x] Undo for individual drawings
- [ ] Crop to square / specific dimensions
- [x] Rotate
- [x] Drag crop area around
- [ ] Save undo stack
- [x] Save button
- [x] Long-press "Download image" doesn't work for large images, consider using blobs with an object URL

**Comment by catdad** [comment]
The rest will be done as needed.
